---
# file: project/example_site.yml

- hosts: all
  become: false
  gather_facts: true
  pre_tasks:

    - set_fact: fact_controller_user="{{ lookup('env','USER') }}"
    - debug: var=fact_controller_user

    - set_fact: fact_controller_home="{{ lookup('env','HOME') }}"
    - debug: var=fact_controller_home

    - set_fact: fact_project_path="{{ lookup('pipe','pwd') }}"
    - debug: var=fact_project_path

- include: sonarqube.yml
